travis:
  secure:
    BINSTAR_TOKEN: x+/i5ugPfzgak9bxiNAJk/OqWwSE1QrnEPVvQ319geHoEekFrVIudeeZtR4LLQ4wDwobeKQmAaVH9J01m1k71OAdMUJqjNQFkYLP6wwq2+fVEW935hXwOE4HvrOYU+MYQNkvfIMPWBb2+wzUHJCwfOOpD8ngWOam8+IlsVcPbURDM0f+pPYy0Ffxtj1SKlYaXbnwvBJZ2qzy6IO6qeokH+j2BbyZykaOvKLKtzGs9qtLCKSdVtyU0NOTE1By1SZosDJjchAP7HjiLjWinJpdP9I13lN7KrrtGnXwHbB1f+YIOB/1RaFd8dFUx4gyTiJr1uOjkP1cgnyrvkKBIOJZ6zCmbrGsM0QRcfSKswGMDK+qJ1ZBzNTkI0Xm4P3eAfMnbdrSrg/ic4oDcfvgCsDoAHnLXAvuYAc3FWbvVP0GzRw2y2By/S4uY8y3f0mIIsBQyUnx0TzAXiOAoScOOywe09hLGu+hsL6u7k4kqvvla9WTbgO58rGxTotGH5Pe4MUPm4K5FZTmAxO0xweQggG0o1weUcHOOOvJx/tT6L5kvzBzgOvL89p8xIQBm1rTxQ8l5+4x+HsLqWnVCrvFsGv/YzNVNQQZfKYkcPUCyCWcvcWNKHVdPR0uLla16SJJKN7rNjGEDZ1CQj7FQzjreKDMtzgjgb3B/bmf1RMzk6Or3tA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
